//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ___VARIABLE_sceneName___BusinessLogic {
    func fetch___VARIABLE_sceneName___(request: ___VARIABLE_sceneName___.Something.Request)
}

protocol ___VARIABLE_sceneName___DataStore {
    //var name: String { get set }
}

final class ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___BusinessLogic, ___VARIABLE_sceneName___DataStore {
    
    var presenter: ___VARIABLE_sceneName___PresentationLogic?
    var worker: ___VARIABLE_sceneName___Worker?
    
    //var name: String = ""
    
    // MARK: Call API for ___VARIABLE_sceneName___
    
    func fetch___VARIABLE_sceneName___(request: ___VARIABLE_sceneName___.Something.Request) {
        worker = ___VARIABLE_sceneName___Worker()
        let response = ___VARIABLE_sceneName___.Something.Response()
        
        worker?.doSomeWork(completion: { [weak self] data, error in
            guard let response = data else { return }
            self?.presenter?..present___VARIABLE_sceneName___Data(response: response)
        })
    }
}
